# Generated by Django 4.2.9 on 2024-01-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_manager',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
